/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IntentRouter {
  export type IntentStruct = {
    id: BytesLike;
    user: AddressLike;
    tokenIn: AddressLike;
    tokenOut: AddressLike;
    amountIn: BigNumberish;
    minAmountOut: BigNumberish;
    sourceChain: BigNumberish;
    destChain: BigNumberish;
    privacy: BigNumberish;
    fragmented: boolean;
    state: BigNumberish;
    timestamp: BigNumberish;
    routeId: BytesLike;
  };

  export type IntentStructOutput = [
    id: string,
    user: string,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    minAmountOut: bigint,
    sourceChain: bigint,
    destChain: bigint,
    privacy: bigint,
    fragmented: boolean,
    state: bigint,
    timestamp: bigint,
    routeId: string
  ] & {
    id: string;
    user: string;
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    minAmountOut: bigint;
    sourceChain: bigint;
    destChain: bigint;
    privacy: bigint;
    fragmented: boolean;
    state: bigint;
    timestamp: bigint;
    routeId: string;
  };
}

export interface IntentRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "GOVERNANCE_ROLE"
      | "ROUTER_ROLE"
      | "createIntent"
      | "failIntent"
      | "fragmentIntent"
      | "getIntent"
      | "getIntentFragments"
      | "getRoleAdmin"
      | "getUserIntents"
      | "grantRole"
      | "hasRole"
      | "intentFragments"
      | "intents"
      | "pause"
      | "paused"
      | "renounceRole"
      | "revokeRole"
      | "routeIntent"
      | "settleIntent"
      | "supportsInterface"
      | "unpause"
      | "userIntents"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "IntentCreated"
      | "IntentFailed"
      | "IntentFragmented"
      | "IntentRouted"
      | "IntentSettled"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNANCE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROUTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createIntent",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "failIntent",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "fragmentIntent",
    values: [BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntentFragments",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserIntents",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "intentFragments",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "intents", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "routeIntent",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleIntent",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userIntents",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNANCE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROUTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "failIntent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fragmentIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getIntent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getIntentFragments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserIntents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "intentFragments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "intents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "routeIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userIntents",
    data: BytesLike
  ): Result;
}

export namespace IntentCreatedEvent {
  export type InputTuple = [
    id: BytesLike,
    user: AddressLike,
    tokenIn: AddressLike,
    tokenOut: AddressLike,
    amountIn: BigNumberish,
    sourceChain: BigNumberish,
    destChain: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    user: string,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    sourceChain: bigint,
    destChain: bigint
  ];
  export interface OutputObject {
    id: string;
    user: string;
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    sourceChain: bigint;
    destChain: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentFailedEvent {
  export type InputTuple = [id: BytesLike, reason: string];
  export type OutputTuple = [id: string, reason: string];
  export interface OutputObject {
    id: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentFragmentedEvent {
  export type InputTuple = [id: BytesLike, fragmentCount: BigNumberish];
  export type OutputTuple = [id: string, fragmentCount: bigint];
  export interface OutputObject {
    id: string;
    fragmentCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentRoutedEvent {
  export type InputTuple = [id: BytesLike, routeId: BytesLike];
  export type OutputTuple = [id: string, routeId: string];
  export interface OutputObject {
    id: string;
    routeId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentSettledEvent {
  export type InputTuple = [
    id: BytesLike,
    amountOut: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [id: string, amountOut: bigint, fee: bigint];
  export interface OutputObject {
    id: string;
    amountOut: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IntentRouter extends BaseContract {
  connect(runner?: ContractRunner | null): IntentRouter;
  waitForDeployment(): Promise<this>;

  interface: IntentRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GOVERNANCE_ROLE: TypedContractMethod<[], [string], "view">;

  ROUTER_ROLE: TypedContractMethod<[], [string], "view">;

  createIntent: TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      sourceChain: BigNumberish,
      destChain: BigNumberish,
      privacy: BigNumberish,
      fragmented: boolean
    ],
    [string],
    "nonpayable"
  >;

  failIntent: TypedContractMethod<
    [intentId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  fragmentIntent: TypedContractMethod<
    [intentId: BytesLike, fragmentIds: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getIntent: TypedContractMethod<
    [id: BytesLike],
    [IntentRouter.IntentStructOutput],
    "view"
  >;

  getIntentFragments: TypedContractMethod<
    [intentId: BytesLike],
    [string[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getUserIntents: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  intentFragments: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  intents: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        string
      ] & {
        id: string;
        user: string;
        tokenIn: string;
        tokenOut: string;
        amountIn: bigint;
        minAmountOut: bigint;
        sourceChain: bigint;
        destChain: bigint;
        privacy: bigint;
        fragmented: boolean;
        state: bigint;
        timestamp: bigint;
        routeId: string;
      }
    ],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  routeIntent: TypedContractMethod<
    [intentId: BytesLike, routeId: BytesLike],
    [void],
    "nonpayable"
  >;

  settleIntent: TypedContractMethod<
    [intentId: BytesLike, amountOut: BigNumberish, fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userIntents: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GOVERNANCE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ROUTER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createIntent"
  ): TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      sourceChain: BigNumberish,
      destChain: BigNumberish,
      privacy: BigNumberish,
      fragmented: boolean
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "failIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fragmentIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, fragmentIds: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getIntent"
  ): TypedContractMethod<
    [id: BytesLike],
    [IntentRouter.IntentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getIntentFragments"
  ): TypedContractMethod<[intentId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUserIntents"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "intentFragments"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "intents"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        string
      ] & {
        id: string;
        user: string;
        tokenIn: string;
        tokenOut: string;
        amountIn: bigint;
        minAmountOut: bigint;
        sourceChain: bigint;
        destChain: bigint;
        privacy: bigint;
        fragmented: boolean;
        state: bigint;
        timestamp: bigint;
        routeId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "routeIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, routeId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleIntent"
  ): TypedContractMethod<
    [intentId: BytesLike, amountOut: BigNumberish, fee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userIntents"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "IntentCreated"
  ): TypedContractEvent<
    IntentCreatedEvent.InputTuple,
    IntentCreatedEvent.OutputTuple,
    IntentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "IntentFailed"
  ): TypedContractEvent<
    IntentFailedEvent.InputTuple,
    IntentFailedEvent.OutputTuple,
    IntentFailedEvent.OutputObject
  >;
  getEvent(
    key: "IntentFragmented"
  ): TypedContractEvent<
    IntentFragmentedEvent.InputTuple,
    IntentFragmentedEvent.OutputTuple,
    IntentFragmentedEvent.OutputObject
  >;
  getEvent(
    key: "IntentRouted"
  ): TypedContractEvent<
    IntentRoutedEvent.InputTuple,
    IntentRoutedEvent.OutputTuple,
    IntentRoutedEvent.OutputObject
  >;
  getEvent(
    key: "IntentSettled"
  ): TypedContractEvent<
    IntentSettledEvent.InputTuple,
    IntentSettledEvent.OutputTuple,
    IntentSettledEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "IntentCreated(bytes32,address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      IntentCreatedEvent.InputTuple,
      IntentCreatedEvent.OutputTuple,
      IntentCreatedEvent.OutputObject
    >;
    IntentCreated: TypedContractEvent<
      IntentCreatedEvent.InputTuple,
      IntentCreatedEvent.OutputTuple,
      IntentCreatedEvent.OutputObject
    >;

    "IntentFailed(bytes32,string)": TypedContractEvent<
      IntentFailedEvent.InputTuple,
      IntentFailedEvent.OutputTuple,
      IntentFailedEvent.OutputObject
    >;
    IntentFailed: TypedContractEvent<
      IntentFailedEvent.InputTuple,
      IntentFailedEvent.OutputTuple,
      IntentFailedEvent.OutputObject
    >;

    "IntentFragmented(bytes32,uint256)": TypedContractEvent<
      IntentFragmentedEvent.InputTuple,
      IntentFragmentedEvent.OutputTuple,
      IntentFragmentedEvent.OutputObject
    >;
    IntentFragmented: TypedContractEvent<
      IntentFragmentedEvent.InputTuple,
      IntentFragmentedEvent.OutputTuple,
      IntentFragmentedEvent.OutputObject
    >;

    "IntentRouted(bytes32,bytes32)": TypedContractEvent<
      IntentRoutedEvent.InputTuple,
      IntentRoutedEvent.OutputTuple,
      IntentRoutedEvent.OutputObject
    >;
    IntentRouted: TypedContractEvent<
      IntentRoutedEvent.InputTuple,
      IntentRoutedEvent.OutputTuple,
      IntentRoutedEvent.OutputObject
    >;

    "IntentSettled(bytes32,uint256,uint256)": TypedContractEvent<
      IntentSettledEvent.InputTuple,
      IntentSettledEvent.OutputTuple,
      IntentSettledEvent.OutputObject
    >;
    IntentSettled: TypedContractEvent<
      IntentSettledEvent.InputTuple,
      IntentSettledEvent.OutputTuple,
      IntentSettledEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
