/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace RelayerRegistry {
  export type RelayerStruct = {
    relayerAddress: AddressLike;
    endpoint: string;
    stake: BigNumberish;
    totalRoutes: BigNumberish;
    successfulRoutes: BigNumberish;
    failedRoutes: BigNumberish;
    totalEarnings: BigNumberish;
    uptime: BigNumberish;
    lastHeartbeat: BigNumberish;
    status: BigNumberish;
    registeredAt: BigNumberish;
    supportedChains: BigNumberish[];
  };

  export type RelayerStructOutput = [
    relayerAddress: string,
    endpoint: string,
    stake: bigint,
    totalRoutes: bigint,
    successfulRoutes: bigint,
    failedRoutes: bigint,
    totalEarnings: bigint,
    uptime: bigint,
    lastHeartbeat: bigint,
    status: bigint,
    registeredAt: bigint,
    supportedChains: bigint[]
  ] & {
    relayerAddress: string;
    endpoint: string;
    stake: bigint;
    totalRoutes: bigint;
    successfulRoutes: bigint;
    failedRoutes: bigint;
    totalEarnings: bigint;
    uptime: bigint;
    lastHeartbeat: bigint;
    status: bigint;
    registeredAt: bigint;
    supportedChains: bigint[];
  };
}

export interface RelayerRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "GOVERNANCE_ROLE"
      | "HEARTBEAT_TIMEOUT"
      | "MIN_STAKE"
      | "REGISTRY_MANAGER_ROLE"
      | "SLASH_THRESHOLD"
      | "activeRelayers"
      | "banRelayer"
      | "chainRelayers"
      | "checkHeartbeats"
      | "getActiveRelayers"
      | "getChainRelayers"
      | "getRelayer"
      | "getRelayerCount"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "heartbeat"
      | "pause"
      | "paused"
      | "recordRouteResult"
      | "registerRelayer"
      | "relayerList"
      | "relayers"
      | "renounceRole"
      | "revokeRole"
      | "slashRelayer"
      | "supportsInterface"
      | "totalRelayers"
      | "unpause"
      | "withdrawStake"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Paused"
      | "RelayerActivated"
      | "RelayerBanned"
      | "RelayerHeartbeat"
      | "RelayerRegistered"
      | "RelayerSlashed"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "RouteAssigned"
      | "RouteCompleted"
      | "StakeIncreased"
      | "StakeWithdrawn"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNANCE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "HEARTBEAT_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_STAKE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "REGISTRY_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SLASH_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeRelayers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "banRelayer",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "chainRelayers",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkHeartbeats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveRelayers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getChainRelayers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRelayerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "heartbeat",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordRouteResult",
    values: [AddressLike, BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "registerRelayer",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "relayerList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "relayers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "slashRelayer",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRelayers",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawStake",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNANCE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "HEARTBEAT_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_STAKE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "REGISTRY_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SLASH_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeRelayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "banRelayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "chainRelayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkHeartbeats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveRelayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChainRelayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRelayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRelayerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "heartbeat", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordRouteResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "relayerList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relayers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "slashRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRelayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStake",
    data: BytesLike
  ): Result;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerActivatedEvent {
  export type InputTuple = [relayer: AddressLike];
  export type OutputTuple = [relayer: string];
  export interface OutputObject {
    relayer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerBannedEvent {
  export type InputTuple = [relayer: AddressLike, reason: string];
  export type OutputTuple = [relayer: string, reason: string];
  export interface OutputObject {
    relayer: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerHeartbeatEvent {
  export type InputTuple = [
    relayer: AddressLike,
    timestamp: BigNumberish,
    blockNumber: BigNumberish,
    signature: BytesLike
  ];
  export type OutputTuple = [
    relayer: string,
    timestamp: bigint,
    blockNumber: bigint,
    signature: string
  ];
  export interface OutputObject {
    relayer: string;
    timestamp: bigint;
    blockNumber: bigint;
    signature: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerRegisteredEvent {
  export type InputTuple = [
    relayer: AddressLike,
    stake: BigNumberish,
    endpoint: string
  ];
  export type OutputTuple = [relayer: string, stake: bigint, endpoint: string];
  export interface OutputObject {
    relayer: string;
    stake: bigint;
    endpoint: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerSlashedEvent {
  export type InputTuple = [
    relayer: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [relayer: string, amount: bigint, reason: string];
  export interface OutputObject {
    relayer: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouteAssignedEvent {
  export type InputTuple = [
    relayer: AddressLike,
    chainId: BigNumberish,
    routeId: BytesLike
  ];
  export type OutputTuple = [relayer: string, chainId: bigint, routeId: string];
  export interface OutputObject {
    relayer: string;
    chainId: bigint;
    routeId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouteCompletedEvent {
  export type InputTuple = [
    relayer: AddressLike,
    routeId: BytesLike,
    success: boolean
  ];
  export type OutputTuple = [
    relayer: string,
    routeId: string,
    success: boolean
  ];
  export interface OutputObject {
    relayer: string;
    routeId: string;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeIncreasedEvent {
  export type InputTuple = [relayer: AddressLike, newTotal: BigNumberish];
  export type OutputTuple = [relayer: string, newTotal: bigint];
  export interface OutputObject {
    relayer: string;
    newTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeWithdrawnEvent {
  export type InputTuple = [relayer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [relayer: string, amount: bigint];
  export interface OutputObject {
    relayer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RelayerRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): RelayerRegistry;
  waitForDeployment(): Promise<this>;

  interface: RelayerRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GOVERNANCE_ROLE: TypedContractMethod<[], [string], "view">;

  HEARTBEAT_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  MIN_STAKE: TypedContractMethod<[], [bigint], "view">;

  REGISTRY_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  SLASH_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  activeRelayers: TypedContractMethod<[], [bigint], "view">;

  banRelayer: TypedContractMethod<
    [relayerAddress: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  chainRelayers: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  checkHeartbeats: TypedContractMethod<[], [void], "nonpayable">;

  getActiveRelayers: TypedContractMethod<[], [string[]], "view">;

  getChainRelayers: TypedContractMethod<
    [chainId: BigNumberish],
    [string[]],
    "view"
  >;

  getRelayer: TypedContractMethod<
    [relayerAddress: AddressLike],
    [RelayerRegistry.RelayerStructOutput],
    "view"
  >;

  getRelayerCount: TypedContractMethod<
    [],
    [[bigint, bigint] & { total: bigint; active: bigint }],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  heartbeat: TypedContractMethod<[signature: BytesLike], [void], "nonpayable">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  recordRouteResult: TypedContractMethod<
    [relayerAddress: AddressLike, routeId: BytesLike, success: boolean],
    [void],
    "nonpayable"
  >;

  registerRelayer: TypedContractMethod<
    [endpoint: string, supportedChains: BigNumberish[]],
    [void],
    "payable"
  >;

  relayerList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  relayers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        relayerAddress: string;
        endpoint: string;
        stake: bigint;
        totalRoutes: bigint;
        successfulRoutes: bigint;
        failedRoutes: bigint;
        totalEarnings: bigint;
        uptime: bigint;
        lastHeartbeat: bigint;
        status: bigint;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  slashRelayer: TypedContractMethod<
    [relayerAddress: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalRelayers: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdrawStake: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GOVERNANCE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "HEARTBEAT_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REGISTRY_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SLASH_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activeRelayers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "banRelayer"
  ): TypedContractMethod<
    [relayerAddress: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "chainRelayers"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkHeartbeats"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveRelayers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getChainRelayers"
  ): TypedContractMethod<[chainId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRelayer"
  ): TypedContractMethod<
    [relayerAddress: AddressLike],
    [RelayerRegistry.RelayerStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRelayerCount"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { total: bigint; active: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "heartbeat"
  ): TypedContractMethod<[signature: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "recordRouteResult"
  ): TypedContractMethod<
    [relayerAddress: AddressLike, routeId: BytesLike, success: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerRelayer"
  ): TypedContractMethod<
    [endpoint: string, supportedChains: BigNumberish[]],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "relayerList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "relayers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        relayerAddress: string;
        endpoint: string;
        stake: bigint;
        totalRoutes: bigint;
        successfulRoutes: bigint;
        failedRoutes: bigint;
        totalEarnings: bigint;
        uptime: bigint;
        lastHeartbeat: bigint;
        status: bigint;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "slashRelayer"
  ): TypedContractMethod<
    [relayerAddress: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalRelayers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawStake"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RelayerActivated"
  ): TypedContractEvent<
    RelayerActivatedEvent.InputTuple,
    RelayerActivatedEvent.OutputTuple,
    RelayerActivatedEvent.OutputObject
  >;
  getEvent(
    key: "RelayerBanned"
  ): TypedContractEvent<
    RelayerBannedEvent.InputTuple,
    RelayerBannedEvent.OutputTuple,
    RelayerBannedEvent.OutputObject
  >;
  getEvent(
    key: "RelayerHeartbeat"
  ): TypedContractEvent<
    RelayerHeartbeatEvent.InputTuple,
    RelayerHeartbeatEvent.OutputTuple,
    RelayerHeartbeatEvent.OutputObject
  >;
  getEvent(
    key: "RelayerRegistered"
  ): TypedContractEvent<
    RelayerRegisteredEvent.InputTuple,
    RelayerRegisteredEvent.OutputTuple,
    RelayerRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RelayerSlashed"
  ): TypedContractEvent<
    RelayerSlashedEvent.InputTuple,
    RelayerSlashedEvent.OutputTuple,
    RelayerSlashedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RouteAssigned"
  ): TypedContractEvent<
    RouteAssignedEvent.InputTuple,
    RouteAssignedEvent.OutputTuple,
    RouteAssignedEvent.OutputObject
  >;
  getEvent(
    key: "RouteCompleted"
  ): TypedContractEvent<
    RouteCompletedEvent.InputTuple,
    RouteCompletedEvent.OutputTuple,
    RouteCompletedEvent.OutputObject
  >;
  getEvent(
    key: "StakeIncreased"
  ): TypedContractEvent<
    StakeIncreasedEvent.InputTuple,
    StakeIncreasedEvent.OutputTuple,
    StakeIncreasedEvent.OutputObject
  >;
  getEvent(
    key: "StakeWithdrawn"
  ): TypedContractEvent<
    StakeWithdrawnEvent.InputTuple,
    StakeWithdrawnEvent.OutputTuple,
    StakeWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RelayerActivated(address)": TypedContractEvent<
      RelayerActivatedEvent.InputTuple,
      RelayerActivatedEvent.OutputTuple,
      RelayerActivatedEvent.OutputObject
    >;
    RelayerActivated: TypedContractEvent<
      RelayerActivatedEvent.InputTuple,
      RelayerActivatedEvent.OutputTuple,
      RelayerActivatedEvent.OutputObject
    >;

    "RelayerBanned(address,string)": TypedContractEvent<
      RelayerBannedEvent.InputTuple,
      RelayerBannedEvent.OutputTuple,
      RelayerBannedEvent.OutputObject
    >;
    RelayerBanned: TypedContractEvent<
      RelayerBannedEvent.InputTuple,
      RelayerBannedEvent.OutputTuple,
      RelayerBannedEvent.OutputObject
    >;

    "RelayerHeartbeat(address,uint256,uint256,bytes32)": TypedContractEvent<
      RelayerHeartbeatEvent.InputTuple,
      RelayerHeartbeatEvent.OutputTuple,
      RelayerHeartbeatEvent.OutputObject
    >;
    RelayerHeartbeat: TypedContractEvent<
      RelayerHeartbeatEvent.InputTuple,
      RelayerHeartbeatEvent.OutputTuple,
      RelayerHeartbeatEvent.OutputObject
    >;

    "RelayerRegistered(address,uint256,string)": TypedContractEvent<
      RelayerRegisteredEvent.InputTuple,
      RelayerRegisteredEvent.OutputTuple,
      RelayerRegisteredEvent.OutputObject
    >;
    RelayerRegistered: TypedContractEvent<
      RelayerRegisteredEvent.InputTuple,
      RelayerRegisteredEvent.OutputTuple,
      RelayerRegisteredEvent.OutputObject
    >;

    "RelayerSlashed(address,uint256,string)": TypedContractEvent<
      RelayerSlashedEvent.InputTuple,
      RelayerSlashedEvent.OutputTuple,
      RelayerSlashedEvent.OutputObject
    >;
    RelayerSlashed: TypedContractEvent<
      RelayerSlashedEvent.InputTuple,
      RelayerSlashedEvent.OutputTuple,
      RelayerSlashedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "RouteAssigned(address,uint256,bytes32)": TypedContractEvent<
      RouteAssignedEvent.InputTuple,
      RouteAssignedEvent.OutputTuple,
      RouteAssignedEvent.OutputObject
    >;
    RouteAssigned: TypedContractEvent<
      RouteAssignedEvent.InputTuple,
      RouteAssignedEvent.OutputTuple,
      RouteAssignedEvent.OutputObject
    >;

    "RouteCompleted(address,bytes32,bool)": TypedContractEvent<
      RouteCompletedEvent.InputTuple,
      RouteCompletedEvent.OutputTuple,
      RouteCompletedEvent.OutputObject
    >;
    RouteCompleted: TypedContractEvent<
      RouteCompletedEvent.InputTuple,
      RouteCompletedEvent.OutputTuple,
      RouteCompletedEvent.OutputObject
    >;

    "StakeIncreased(address,uint256)": TypedContractEvent<
      StakeIncreasedEvent.InputTuple,
      StakeIncreasedEvent.OutputTuple,
      StakeIncreasedEvent.OutputObject
    >;
    StakeIncreased: TypedContractEvent<
      StakeIncreasedEvent.InputTuple,
      StakeIncreasedEvent.OutputTuple,
      StakeIncreasedEvent.OutputObject
    >;

    "StakeWithdrawn(address,uint256)": TypedContractEvent<
      StakeWithdrawnEvent.InputTuple,
      StakeWithdrawnEvent.OutputTuple,
      StakeWithdrawnEvent.OutputObject
    >;
    StakeWithdrawn: TypedContractEvent<
      StakeWithdrawnEvent.InputTuple,
      StakeWithdrawnEvent.OutputTuple,
      StakeWithdrawnEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
