/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace RouteRegistry {
  export type RouteStruct = {
    id: BytesLike;
    name: string;
    sourceChain: BigNumberish;
    destChain: BigNumberish;
    bridges: AddressLike[];
    dexes: AddressLike[];
    maxAmount: BigNumberish;
    minAmount: BigNumberish;
    avgLatency: BigNumberish;
    successRate: BigNumberish;
    totalVolume: BigNumberish;
    totalExecutions: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type RouteStructOutput = [
    id: string,
    name: string,
    sourceChain: bigint,
    destChain: bigint,
    bridges: string[],
    dexes: string[],
    maxAmount: bigint,
    minAmount: bigint,
    avgLatency: bigint,
    successRate: bigint,
    totalVolume: bigint,
    totalExecutions: bigint,
    status: bigint,
    createdAt: bigint,
    updatedAt: bigint
  ] & {
    id: string;
    name: string;
    sourceChain: bigint;
    destChain: bigint;
    bridges: string[];
    dexes: string[];
    maxAmount: bigint;
    minAmount: bigint;
    avgLatency: bigint;
    successRate: bigint;
    totalVolume: bigint;
    totalExecutions: bigint;
    status: bigint;
    createdAt: bigint;
    updatedAt: bigint;
  };
}

export interface RouteRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "GOVERNANCE_ROLE"
      | "ROUTE_MANAGER_ROLE"
      | "allRoutes"
      | "chainRoutes"
      | "getAllRoutes"
      | "getChainRoutes"
      | "getRoleAdmin"
      | "getRoute"
      | "getRouteCount"
      | "grantRole"
      | "hasRole"
      | "pause"
      | "paused"
      | "recordExecution"
      | "registerRoute"
      | "renounceRole"
      | "revokeRole"
      | "routes"
      | "supportsInterface"
      | "unpause"
      | "updateRouteStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "RouteExecuted"
      | "RouteRegistered"
      | "RouteRetired"
      | "RouteUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNANCE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROUTE_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allRoutes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "chainRoutes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllRoutes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getChainRoutes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getRoute", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getRouteCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordExecution",
    values: [BytesLike, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "registerRoute",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      AddressLike[],
      AddressLike[],
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "routes", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateRouteStatus",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNANCE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROUTE_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allRoutes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "chainRoutes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllRoutes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChainRoutes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRoute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRouteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerRoute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "routes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateRouteStatus",
    data: BytesLike
  ): Result;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouteExecutedEvent {
  export type InputTuple = [
    id: BytesLike,
    amount: BigNumberish,
    latency: BigNumberish,
    success: boolean
  ];
  export type OutputTuple = [
    id: string,
    amount: bigint,
    latency: bigint,
    success: boolean
  ];
  export interface OutputObject {
    id: string;
    amount: bigint;
    latency: bigint;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouteRegisteredEvent {
  export type InputTuple = [
    id: BytesLike,
    name: string,
    sourceChain: BigNumberish,
    destChain: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    name: string,
    sourceChain: bigint,
    destChain: bigint
  ];
  export interface OutputObject {
    id: string;
    name: string;
    sourceChain: bigint;
    destChain: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouteRetiredEvent {
  export type InputTuple = [id: BytesLike];
  export type OutputTuple = [id: string];
  export interface OutputObject {
    id: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouteUpdatedEvent {
  export type InputTuple = [id: BytesLike, status: BigNumberish];
  export type OutputTuple = [id: string, status: bigint];
  export interface OutputObject {
    id: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RouteRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): RouteRegistry;
  waitForDeployment(): Promise<this>;

  interface: RouteRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GOVERNANCE_ROLE: TypedContractMethod<[], [string], "view">;

  ROUTE_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  allRoutes: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  chainRoutes: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  getAllRoutes: TypedContractMethod<[], [string[]], "view">;

  getChainRoutes: TypedContractMethod<
    [chainId: BigNumberish],
    [string[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getRoute: TypedContractMethod<
    [id: BytesLike],
    [RouteRegistry.RouteStructOutput],
    "view"
  >;

  getRouteCount: TypedContractMethod<[], [bigint], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  recordExecution: TypedContractMethod<
    [
      routeId: BytesLike,
      amount: BigNumberish,
      latency: BigNumberish,
      success: boolean
    ],
    [void],
    "nonpayable"
  >;

  registerRoute: TypedContractMethod<
    [
      name: string,
      sourceChain: BigNumberish,
      destChain: BigNumberish,
      bridges: AddressLike[],
      dexes: AddressLike[],
      maxAmount: BigNumberish,
      minAmount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  routes: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: string;
        name: string;
        sourceChain: bigint;
        destChain: bigint;
        maxAmount: bigint;
        minAmount: bigint;
        avgLatency: bigint;
        successRate: bigint;
        totalVolume: bigint;
        totalExecutions: bigint;
        status: bigint;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateRouteStatus: TypedContractMethod<
    [routeId: BytesLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GOVERNANCE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ROUTE_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allRoutes"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "chainRoutes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllRoutes"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getChainRoutes"
  ): TypedContractMethod<[chainId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRoute"
  ): TypedContractMethod<
    [id: BytesLike],
    [RouteRegistry.RouteStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRouteCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "recordExecution"
  ): TypedContractMethod<
    [
      routeId: BytesLike,
      amount: BigNumberish,
      latency: BigNumberish,
      success: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerRoute"
  ): TypedContractMethod<
    [
      name: string,
      sourceChain: BigNumberish,
      destChain: BigNumberish,
      bridges: AddressLike[],
      dexes: AddressLike[],
      maxAmount: BigNumberish,
      minAmount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "routes"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: string;
        name: string;
        sourceChain: bigint;
        destChain: bigint;
        maxAmount: bigint;
        minAmount: bigint;
        avgLatency: bigint;
        successRate: bigint;
        totalVolume: bigint;
        totalExecutions: bigint;
        status: bigint;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRouteStatus"
  ): TypedContractMethod<
    [routeId: BytesLike, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RouteExecuted"
  ): TypedContractEvent<
    RouteExecutedEvent.InputTuple,
    RouteExecutedEvent.OutputTuple,
    RouteExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RouteRegistered"
  ): TypedContractEvent<
    RouteRegisteredEvent.InputTuple,
    RouteRegisteredEvent.OutputTuple,
    RouteRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RouteRetired"
  ): TypedContractEvent<
    RouteRetiredEvent.InputTuple,
    RouteRetiredEvent.OutputTuple,
    RouteRetiredEvent.OutputObject
  >;
  getEvent(
    key: "RouteUpdated"
  ): TypedContractEvent<
    RouteUpdatedEvent.InputTuple,
    RouteUpdatedEvent.OutputTuple,
    RouteUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "RouteExecuted(bytes32,uint256,uint256,bool)": TypedContractEvent<
      RouteExecutedEvent.InputTuple,
      RouteExecutedEvent.OutputTuple,
      RouteExecutedEvent.OutputObject
    >;
    RouteExecuted: TypedContractEvent<
      RouteExecutedEvent.InputTuple,
      RouteExecutedEvent.OutputTuple,
      RouteExecutedEvent.OutputObject
    >;

    "RouteRegistered(bytes32,string,uint256,uint256)": TypedContractEvent<
      RouteRegisteredEvent.InputTuple,
      RouteRegisteredEvent.OutputTuple,
      RouteRegisteredEvent.OutputObject
    >;
    RouteRegistered: TypedContractEvent<
      RouteRegisteredEvent.InputTuple,
      RouteRegisteredEvent.OutputTuple,
      RouteRegisteredEvent.OutputObject
    >;

    "RouteRetired(bytes32)": TypedContractEvent<
      RouteRetiredEvent.InputTuple,
      RouteRetiredEvent.OutputTuple,
      RouteRetiredEvent.OutputObject
    >;
    RouteRetired: TypedContractEvent<
      RouteRetiredEvent.InputTuple,
      RouteRetiredEvent.OutputTuple,
      RouteRetiredEvent.OutputObject
    >;

    "RouteUpdated(bytes32,uint8)": TypedContractEvent<
      RouteUpdatedEvent.InputTuple,
      RouteUpdatedEvent.OutputTuple,
      RouteUpdatedEvent.OutputObject
    >;
    RouteUpdated: TypedContractEvent<
      RouteUpdatedEvent.InputTuple,
      RouteUpdatedEvent.OutputTuple,
      RouteUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
