/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SettlementVerifier {
  export type SettlementProofStruct = {
    txHash: BytesLike;
    routeId: BytesLike;
    proofHash: BytesLike;
    sourceChainBlockHash: BytesLike;
    destChainBlockHash: BytesLike;
    relayer: AddressLike;
    amount: BigNumberish;
    fee: BigNumberish;
    sourceConfirmations: BigNumberish;
    destConfirmations: BigNumberish;
    state: BigNumberish;
    timestamp: BigNumberish;
    finalizedAt: BigNumberish;
  };

  export type SettlementProofStructOutput = [
    txHash: string,
    routeId: string,
    proofHash: string,
    sourceChainBlockHash: string,
    destChainBlockHash: string,
    relayer: string,
    amount: bigint,
    fee: bigint,
    sourceConfirmations: bigint,
    destConfirmations: bigint,
    state: bigint,
    timestamp: bigint,
    finalizedAt: bigint
  ] & {
    txHash: string;
    routeId: string;
    proofHash: string;
    sourceChainBlockHash: string;
    destChainBlockHash: string;
    relayer: string;
    amount: bigint;
    fee: bigint;
    sourceConfirmations: bigint;
    destConfirmations: bigint;
    state: bigint;
    timestamp: bigint;
    finalizedAt: bigint;
  };
}

export interface SettlementVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "FINALIZATION_PERIOD"
      | "GOVERNANCE_ROLE"
      | "MIN_CONFIRMATIONS"
      | "VERIFIER_ROLE"
      | "completeVerification"
      | "confirmProof"
      | "disputeProof"
      | "finalizeProof"
      | "getProof"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "isTxVerified"
      | "proofs"
      | "renounceRole"
      | "requestVerification"
      | "revokeRole"
      | "submitProof"
      | "supportsInterface"
      | "verificationRequests"
      | "verifiedTxHashes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ProofConfirmed"
      | "ProofDisputed"
      | "ProofFinalized"
      | "ProofSubmitted"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "VerificationCompleted"
      | "VerificationRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FINALIZATION_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNANCE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_CONFIRMATIONS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFIER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "completeVerification",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmProof",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeProof",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeProof",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getProof", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTxVerified",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "proofs", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestVerification",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationRequests",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedTxHashes",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FINALIZATION_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNANCE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_CONFIRMATIONS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFIER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProof", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTxVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proofs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedTxHashes",
    data: BytesLike
  ): Result;
}

export namespace ProofConfirmedEvent {
  export type InputTuple = [txHash: BytesLike, confirmations: BigNumberish];
  export type OutputTuple = [txHash: string, confirmations: bigint];
  export interface OutputObject {
    txHash: string;
    confirmations: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofDisputedEvent {
  export type InputTuple = [txHash: BytesLike, reason: string];
  export type OutputTuple = [txHash: string, reason: string];
  export interface OutputObject {
    txHash: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofFinalizedEvent {
  export type InputTuple = [txHash: BytesLike];
  export type OutputTuple = [txHash: string];
  export interface OutputObject {
    txHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProofSubmittedEvent {
  export type InputTuple = [
    txHash: BytesLike,
    routeId: BytesLike,
    proofHash: BytesLike,
    relayer: AddressLike
  ];
  export type OutputTuple = [
    txHash: string,
    routeId: string,
    proofHash: string,
    relayer: string
  ];
  export interface OutputObject {
    txHash: string;
    routeId: string;
    proofHash: string;
    relayer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationCompletedEvent {
  export type InputTuple = [id: BytesLike, verified: boolean];
  export type OutputTuple = [id: string, verified: boolean];
  export interface OutputObject {
    id: string;
    verified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerificationRequestedEvent {
  export type InputTuple = [
    id: BytesLike,
    txHash: BytesLike,
    requester: AddressLike
  ];
  export type OutputTuple = [id: string, txHash: string, requester: string];
  export interface OutputObject {
    id: string;
    txHash: string;
    requester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SettlementVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): SettlementVerifier;
  waitForDeployment(): Promise<this>;

  interface: SettlementVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  FINALIZATION_PERIOD: TypedContractMethod<[], [bigint], "view">;

  GOVERNANCE_ROLE: TypedContractMethod<[], [string], "view">;

  MIN_CONFIRMATIONS: TypedContractMethod<[], [bigint], "view">;

  VERIFIER_ROLE: TypedContractMethod<[], [string], "view">;

  completeVerification: TypedContractMethod<
    [requestId: BytesLike, verified: boolean],
    [void],
    "nonpayable"
  >;

  confirmProof: TypedContractMethod<
    [txHash: BytesLike, sourceConfs: BigNumberish, destConfs: BigNumberish],
    [void],
    "nonpayable"
  >;

  disputeProof: TypedContractMethod<
    [txHash: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  finalizeProof: TypedContractMethod<[txHash: BytesLike], [void], "nonpayable">;

  getProof: TypedContractMethod<
    [txHash: BytesLike],
    [SettlementVerifier.SettlementProofStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isTxVerified: TypedContractMethod<[txHash: BytesLike], [boolean], "view">;

  proofs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        txHash: string;
        routeId: string;
        proofHash: string;
        sourceChainBlockHash: string;
        destChainBlockHash: string;
        relayer: string;
        amount: bigint;
        fee: bigint;
        sourceConfirmations: bigint;
        destConfirmations: bigint;
        state: bigint;
        timestamp: bigint;
        finalizedAt: bigint;
      }
    ],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestVerification: TypedContractMethod<
    [txHash: BytesLike],
    [string],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  submitProof: TypedContractMethod<
    [
      txHash: BytesLike,
      routeId: BytesLike,
      proofHash: BytesLike,
      sourceChainBlockHash: BytesLike,
      destChainBlockHash: BytesLike,
      amount: BigNumberish,
      fee: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  verificationRequests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, boolean] & {
        id: string;
        txHash: string;
        routeId: string;
        requester: string;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;

  verifiedTxHashes: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FINALIZATION_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GOVERNANCE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MIN_CONFIRMATIONS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERIFIER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "completeVerification"
  ): TypedContractMethod<
    [requestId: BytesLike, verified: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confirmProof"
  ): TypedContractMethod<
    [txHash: BytesLike, sourceConfs: BigNumberish, destConfs: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputeProof"
  ): TypedContractMethod<
    [txHash: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeProof"
  ): TypedContractMethod<[txHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getProof"
  ): TypedContractMethod<
    [txHash: BytesLike],
    [SettlementVerifier.SettlementProofStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTxVerified"
  ): TypedContractMethod<[txHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "proofs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        txHash: string;
        routeId: string;
        proofHash: string;
        sourceChainBlockHash: string;
        destChainBlockHash: string;
        relayer: string;
        amount: bigint;
        fee: bigint;
        sourceConfirmations: bigint;
        destConfirmations: bigint;
        state: bigint;
        timestamp: bigint;
        finalizedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestVerification"
  ): TypedContractMethod<[txHash: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<
    [
      txHash: BytesLike,
      routeId: BytesLike,
      proofHash: BytesLike,
      sourceChainBlockHash: BytesLike,
      destChainBlockHash: BytesLike,
      amount: BigNumberish,
      fee: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verificationRequests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, boolean] & {
        id: string;
        txHash: string;
        routeId: string;
        requester: string;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifiedTxHashes"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "ProofConfirmed"
  ): TypedContractEvent<
    ProofConfirmedEvent.InputTuple,
    ProofConfirmedEvent.OutputTuple,
    ProofConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "ProofDisputed"
  ): TypedContractEvent<
    ProofDisputedEvent.InputTuple,
    ProofDisputedEvent.OutputTuple,
    ProofDisputedEvent.OutputObject
  >;
  getEvent(
    key: "ProofFinalized"
  ): TypedContractEvent<
    ProofFinalizedEvent.InputTuple,
    ProofFinalizedEvent.OutputTuple,
    ProofFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "ProofSubmitted"
  ): TypedContractEvent<
    ProofSubmittedEvent.InputTuple,
    ProofSubmittedEvent.OutputTuple,
    ProofSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationCompleted"
  ): TypedContractEvent<
    VerificationCompletedEvent.InputTuple,
    VerificationCompletedEvent.OutputTuple,
    VerificationCompletedEvent.OutputObject
  >;
  getEvent(
    key: "VerificationRequested"
  ): TypedContractEvent<
    VerificationRequestedEvent.InputTuple,
    VerificationRequestedEvent.OutputTuple,
    VerificationRequestedEvent.OutputObject
  >;

  filters: {
    "ProofConfirmed(bytes32,uint256)": TypedContractEvent<
      ProofConfirmedEvent.InputTuple,
      ProofConfirmedEvent.OutputTuple,
      ProofConfirmedEvent.OutputObject
    >;
    ProofConfirmed: TypedContractEvent<
      ProofConfirmedEvent.InputTuple,
      ProofConfirmedEvent.OutputTuple,
      ProofConfirmedEvent.OutputObject
    >;

    "ProofDisputed(bytes32,string)": TypedContractEvent<
      ProofDisputedEvent.InputTuple,
      ProofDisputedEvent.OutputTuple,
      ProofDisputedEvent.OutputObject
    >;
    ProofDisputed: TypedContractEvent<
      ProofDisputedEvent.InputTuple,
      ProofDisputedEvent.OutputTuple,
      ProofDisputedEvent.OutputObject
    >;

    "ProofFinalized(bytes32)": TypedContractEvent<
      ProofFinalizedEvent.InputTuple,
      ProofFinalizedEvent.OutputTuple,
      ProofFinalizedEvent.OutputObject
    >;
    ProofFinalized: TypedContractEvent<
      ProofFinalizedEvent.InputTuple,
      ProofFinalizedEvent.OutputTuple,
      ProofFinalizedEvent.OutputObject
    >;

    "ProofSubmitted(bytes32,bytes32,bytes32,address)": TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;
    ProofSubmitted: TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "VerificationCompleted(bytes32,bool)": TypedContractEvent<
      VerificationCompletedEvent.InputTuple,
      VerificationCompletedEvent.OutputTuple,
      VerificationCompletedEvent.OutputObject
    >;
    VerificationCompleted: TypedContractEvent<
      VerificationCompletedEvent.InputTuple,
      VerificationCompletedEvent.OutputTuple,
      VerificationCompletedEvent.OutputObject
    >;

    "VerificationRequested(bytes32,bytes32,address)": TypedContractEvent<
      VerificationRequestedEvent.InputTuple,
      VerificationRequestedEvent.OutputTuple,
      VerificationRequestedEvent.OutputObject
    >;
    VerificationRequested: TypedContractEvent<
      VerificationRequestedEvent.InputTuple,
      VerificationRequestedEvent.OutputTuple,
      VerificationRequestedEvent.OutputObject
    >;
  };
}
