/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SolverAuction {
  export type BidStruct = {
    id: BytesLike;
    auctionId: BytesLike;
    solver: AddressLike;
    price: BigNumberish;
    estimatedGas: BigNumberish;
    executionTime: BigNumberish;
    routeId: BytesLike;
    state: BigNumberish;
    submittedAt: BigNumberish;
  };

  export type BidStructOutput = [
    id: string,
    auctionId: string,
    solver: string,
    price: bigint,
    estimatedGas: bigint,
    executionTime: bigint,
    routeId: string,
    state: bigint,
    submittedAt: bigint
  ] & {
    id: string;
    auctionId: string;
    solver: string;
    price: bigint;
    estimatedGas: bigint;
    executionTime: bigint;
    routeId: string;
    state: bigint;
    submittedAt: bigint;
  };
}

export interface SolverAuctionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AUCTION_DURATION"
      | "AUCTION_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "FEE_BPS"
      | "GOVERNANCE_ROLE"
      | "MIN_STAKE"
      | "acceptBid"
      | "auctionBids"
      | "auctions"
      | "cancelAuction"
      | "createAuction"
      | "getActiveSolvers"
      | "getAuctionBids"
      | "getRoleAdmin"
      | "getSolverAuctions"
      | "grantRole"
      | "hasBid"
      | "hasRole"
      | "pause"
      | "paused"
      | "registerSolver"
      | "renounceRole"
      | "revokeRole"
      | "settleAuctionDutch"
      | "solverAuctions"
      | "solvers"
      | "submitBid"
      | "supportsInterface"
      | "unpause"
      | "unregisterSolver"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuctionCancelled"
      | "AuctionCreated"
      | "AuctionSettled"
      | "BidAccepted"
      | "BidRejected"
      | "BidSubmitted"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SolverRegistered"
      | "SolverStakeUpdated"
      | "SolverUnregistered"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AUCTION_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "AUCTION_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "FEE_BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "GOVERNANCE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_STAKE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "acceptBid",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "auctionBids",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "auctions", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "cancelAuction",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createAuction",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveSolvers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAuctionBids",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSolverAuctions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasBid",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerSolver",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleAuctionDutch",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "solverAuctions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "solvers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBid",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unregisterSolver",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "AUCTION_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "AUCTION_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "FEE_BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNANCE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_STAKE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "acceptBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "auctionBids",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "auctions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveSolvers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuctionBids",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSolverAuctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerSolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settleAuctionDutch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "solverAuctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "solvers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submitBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unregisterSolver",
    data: BytesLike
  ): Result;
}

export namespace AuctionCancelledEvent {
  export type InputTuple = [auctionId: BytesLike];
  export type OutputTuple = [auctionId: string];
  export interface OutputObject {
    auctionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionCreatedEvent {
  export type InputTuple = [
    id: BytesLike,
    intentId: BytesLike,
    startPrice: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    intentId: string,
    startPrice: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    id: string;
    intentId: string;
    startPrice: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionSettledEvent {
  export type InputTuple = [
    auctionId: BytesLike,
    winner: AddressLike,
    finalPrice: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: string,
    winner: string,
    finalPrice: bigint
  ];
  export interface OutputObject {
    auctionId: string;
    winner: string;
    finalPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidAcceptedEvent {
  export type InputTuple = [
    auctionId: BytesLike,
    solver: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [auctionId: string, solver: string, price: bigint];
  export interface OutputObject {
    auctionId: string;
    solver: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidRejectedEvent {
  export type InputTuple = [auctionId: BytesLike, solver: AddressLike];
  export type OutputTuple = [auctionId: string, solver: string];
  export interface OutputObject {
    auctionId: string;
    solver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidSubmittedEvent {
  export type InputTuple = [
    auctionId: BytesLike,
    solver: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [auctionId: string, solver: string, price: bigint];
  export interface OutputObject {
    auctionId: string;
    solver: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SolverRegisteredEvent {
  export type InputTuple = [solver: AddressLike, stakeAmount: BigNumberish];
  export type OutputTuple = [solver: string, stakeAmount: bigint];
  export interface OutputObject {
    solver: string;
    stakeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SolverStakeUpdatedEvent {
  export type InputTuple = [solver: AddressLike, newStake: BigNumberish];
  export type OutputTuple = [solver: string, newStake: bigint];
  export interface OutputObject {
    solver: string;
    newStake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SolverUnregisteredEvent {
  export type InputTuple = [solver: AddressLike];
  export type OutputTuple = [solver: string];
  export interface OutputObject {
    solver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SolverAuction extends BaseContract {
  connect(runner?: ContractRunner | null): SolverAuction;
  waitForDeployment(): Promise<this>;

  interface: SolverAuctionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AUCTION_DURATION: TypedContractMethod<[], [bigint], "view">;

  AUCTION_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  GOVERNANCE_ROLE: TypedContractMethod<[], [string], "view">;

  MIN_STAKE: TypedContractMethod<[], [bigint], "view">;

  acceptBid: TypedContractMethod<
    [auctionId: BytesLike, bidId: BytesLike],
    [void],
    "nonpayable"
  >;

  auctionBids: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        id: string;
        auctionId: string;
        solver: string;
        price: bigint;
        estimatedGas: bigint;
        executionTime: bigint;
        routeId: string;
        state: bigint;
        submittedAt: bigint;
      }
    ],
    "view"
  >;

  auctions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        id: string;
        intentId: string;
        tokenIn: string;
        tokenOut: string;
        amountIn: bigint;
        startPrice: bigint;
        endPrice: bigint;
        currentPrice: bigint;
        deadline: bigint;
        settledAt: bigint;
        state: bigint;
        winner: string;
        finalPrice: bigint;
        solverFee: bigint;
      }
    ],
    "view"
  >;

  cancelAuction: TypedContractMethod<
    [auctionId: BytesLike],
    [void],
    "nonpayable"
  >;

  createAuction: TypedContractMethod<
    [
      intentId: BytesLike,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      startPrice: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getActiveSolvers: TypedContractMethod<[], [string[]], "view">;

  getAuctionBids: TypedContractMethod<
    [auctionId: BytesLike],
    [SolverAuction.BidStructOutput[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSolverAuctions: TypedContractMethod<
    [solver: AddressLike],
    [string[]],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasBid: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  registerSolver: TypedContractMethod<
    [solver: AddressLike, stakeAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  settleAuctionDutch: TypedContractMethod<
    [auctionId: BytesLike],
    [void],
    "nonpayable"
  >;

  solverAuctions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  solvers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean, bigint] & {
        addr: string;
        stakedAmount: bigint;
        totalSolved: bigint;
        successRate: bigint;
        averageExecutionTime: bigint;
        isActive: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  submitBid: TypedContractMethod<
    [
      auctionId: BytesLike,
      price: BigNumberish,
      estimatedGas: BigNumberish,
      executionTime: BigNumberish,
      routeId: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  unregisterSolver: TypedContractMethod<
    [solver: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AUCTION_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "AUCTION_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GOVERNANCE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MIN_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptBid"
  ): TypedContractMethod<
    [auctionId: BytesLike, bidId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "auctionBids"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        id: string;
        auctionId: string;
        solver: string;
        price: bigint;
        estimatedGas: bigint;
        executionTime: bigint;
        routeId: string;
        state: bigint;
        submittedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "auctions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        id: string;
        intentId: string;
        tokenIn: string;
        tokenOut: string;
        amountIn: bigint;
        startPrice: bigint;
        endPrice: bigint;
        currentPrice: bigint;
        deadline: bigint;
        settledAt: bigint;
        state: bigint;
        winner: string;
        finalPrice: bigint;
        solverFee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelAuction"
  ): TypedContractMethod<[auctionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createAuction"
  ): TypedContractMethod<
    [
      intentId: BytesLike,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      startPrice: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveSolvers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAuctionBids"
  ): TypedContractMethod<
    [auctionId: BytesLike],
    [SolverAuction.BidStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSolverAuctions"
  ): TypedContractMethod<[solver: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasBid"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerSolver"
  ): TypedContractMethod<
    [solver: AddressLike, stakeAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleAuctionDutch"
  ): TypedContractMethod<[auctionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "solverAuctions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "solvers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean, bigint] & {
        addr: string;
        stakedAmount: bigint;
        totalSolved: bigint;
        successRate: bigint;
        averageExecutionTime: bigint;
        isActive: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitBid"
  ): TypedContractMethod<
    [
      auctionId: BytesLike,
      price: BigNumberish,
      estimatedGas: BigNumberish,
      executionTime: BigNumberish,
      routeId: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unregisterSolver"
  ): TypedContractMethod<[solver: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AuctionCancelled"
  ): TypedContractEvent<
    AuctionCancelledEvent.InputTuple,
    AuctionCancelledEvent.OutputTuple,
    AuctionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "AuctionCreated"
  ): TypedContractEvent<
    AuctionCreatedEvent.InputTuple,
    AuctionCreatedEvent.OutputTuple,
    AuctionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionSettled"
  ): TypedContractEvent<
    AuctionSettledEvent.InputTuple,
    AuctionSettledEvent.OutputTuple,
    AuctionSettledEvent.OutputObject
  >;
  getEvent(
    key: "BidAccepted"
  ): TypedContractEvent<
    BidAcceptedEvent.InputTuple,
    BidAcceptedEvent.OutputTuple,
    BidAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "BidRejected"
  ): TypedContractEvent<
    BidRejectedEvent.InputTuple,
    BidRejectedEvent.OutputTuple,
    BidRejectedEvent.OutputObject
  >;
  getEvent(
    key: "BidSubmitted"
  ): TypedContractEvent<
    BidSubmittedEvent.InputTuple,
    BidSubmittedEvent.OutputTuple,
    BidSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SolverRegistered"
  ): TypedContractEvent<
    SolverRegisteredEvent.InputTuple,
    SolverRegisteredEvent.OutputTuple,
    SolverRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "SolverStakeUpdated"
  ): TypedContractEvent<
    SolverStakeUpdatedEvent.InputTuple,
    SolverStakeUpdatedEvent.OutputTuple,
    SolverStakeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SolverUnregistered"
  ): TypedContractEvent<
    SolverUnregisteredEvent.InputTuple,
    SolverUnregisteredEvent.OutputTuple,
    SolverUnregisteredEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AuctionCancelled(bytes32)": TypedContractEvent<
      AuctionCancelledEvent.InputTuple,
      AuctionCancelledEvent.OutputTuple,
      AuctionCancelledEvent.OutputObject
    >;
    AuctionCancelled: TypedContractEvent<
      AuctionCancelledEvent.InputTuple,
      AuctionCancelledEvent.OutputTuple,
      AuctionCancelledEvent.OutputObject
    >;

    "AuctionCreated(bytes32,bytes32,uint256,uint256)": TypedContractEvent<
      AuctionCreatedEvent.InputTuple,
      AuctionCreatedEvent.OutputTuple,
      AuctionCreatedEvent.OutputObject
    >;
    AuctionCreated: TypedContractEvent<
      AuctionCreatedEvent.InputTuple,
      AuctionCreatedEvent.OutputTuple,
      AuctionCreatedEvent.OutputObject
    >;

    "AuctionSettled(bytes32,address,uint256)": TypedContractEvent<
      AuctionSettledEvent.InputTuple,
      AuctionSettledEvent.OutputTuple,
      AuctionSettledEvent.OutputObject
    >;
    AuctionSettled: TypedContractEvent<
      AuctionSettledEvent.InputTuple,
      AuctionSettledEvent.OutputTuple,
      AuctionSettledEvent.OutputObject
    >;

    "BidAccepted(bytes32,address,uint256)": TypedContractEvent<
      BidAcceptedEvent.InputTuple,
      BidAcceptedEvent.OutputTuple,
      BidAcceptedEvent.OutputObject
    >;
    BidAccepted: TypedContractEvent<
      BidAcceptedEvent.InputTuple,
      BidAcceptedEvent.OutputTuple,
      BidAcceptedEvent.OutputObject
    >;

    "BidRejected(bytes32,address)": TypedContractEvent<
      BidRejectedEvent.InputTuple,
      BidRejectedEvent.OutputTuple,
      BidRejectedEvent.OutputObject
    >;
    BidRejected: TypedContractEvent<
      BidRejectedEvent.InputTuple,
      BidRejectedEvent.OutputTuple,
      BidRejectedEvent.OutputObject
    >;

    "BidSubmitted(bytes32,address,uint256)": TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;
    BidSubmitted: TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SolverRegistered(address,uint256)": TypedContractEvent<
      SolverRegisteredEvent.InputTuple,
      SolverRegisteredEvent.OutputTuple,
      SolverRegisteredEvent.OutputObject
    >;
    SolverRegistered: TypedContractEvent<
      SolverRegisteredEvent.InputTuple,
      SolverRegisteredEvent.OutputTuple,
      SolverRegisteredEvent.OutputObject
    >;

    "SolverStakeUpdated(address,uint256)": TypedContractEvent<
      SolverStakeUpdatedEvent.InputTuple,
      SolverStakeUpdatedEvent.OutputTuple,
      SolverStakeUpdatedEvent.OutputObject
    >;
    SolverStakeUpdated: TypedContractEvent<
      SolverStakeUpdatedEvent.InputTuple,
      SolverStakeUpdatedEvent.OutputTuple,
      SolverStakeUpdatedEvent.OutputObject
    >;

    "SolverUnregistered(address)": TypedContractEvent<
      SolverUnregisteredEvent.InputTuple,
      SolverUnregisteredEvent.OutputTuple,
      SolverUnregisteredEvent.OutputObject
    >;
    SolverUnregistered: TypedContractEvent<
      SolverUnregisteredEvent.InputTuple,
      SolverUnregisteredEvent.OutputTuple,
      SolverUnregisteredEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
