/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TreasuryFeeCollector {
  export type FeeCollectionStruct = {
    token: AddressLike;
    totalCollected: BigNumberish;
    distributedToRelayers: BigNumberish;
    distributedToTreasury: BigNumberish;
    lastCollection: BigNumberish;
  };

  export type FeeCollectionStructOutput = [
    token: string,
    totalCollected: bigint,
    distributedToRelayers: bigint,
    distributedToTreasury: bigint,
    lastCollection: bigint
  ] & {
    token: string;
    totalCollected: bigint;
    distributedToRelayers: bigint;
    distributedToTreasury: bigint;
    lastCollection: bigint;
  };
}

export interface TreasuryFeeCollectorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "DEFAULT_ADMIN_ROLE"
      | "FEE_MANAGER_ROLE"
      | "GOVERNANCE_ROLE"
      | "MAX_FEE_BPS"
      | "addFeeTier"
      | "chainFeeConfigs"
      | "collectFee"
      | "distributeToTreasury"
      | "feeTiers"
      | "getFee"
      | "getFeeForAmount"
      | "getRoleAdmin"
      | "getTokenFees"
      | "grantRole"
      | "hasRole"
      | "minFeeTier"
      | "renounceRole"
      | "revokeRole"
      | "routeFees"
      | "setFeeConfig"
      | "setTreasuryWallet"
      | "supportsInterface"
      | "tokenFees"
      | "treasuryWallet"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeCollected"
      | "FeeConfigUpdated"
      | "FeeDistributed"
      | "FeeTierAdded"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TreasuryWalletUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEE_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNANCE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addFeeTier",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "chainFeeConfigs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectFee",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeToTreasury",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeTiers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getFee", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getFeeForAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "minFeeTier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "routeFees",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeConfig",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuryWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryWallet",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEE_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNANCE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addFeeTier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "chainFeeConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "collectFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeToTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeTiers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFeeForAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minFeeTier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "routeFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuryWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "treasuryWallet",
    data: BytesLike
  ): Result;
}

export namespace FeeCollectedEvent {
  export type InputTuple = [
    routeId: BytesLike,
    token: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    routeId: string,
    token: string,
    amount: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    routeId: string;
    token: string;
    amount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeConfigUpdatedEvent {
  export type InputTuple = [
    chainId: BigNumberish,
    protocolFeeBps: BigNumberish
  ];
  export type OutputTuple = [chainId: bigint, protocolFeeBps: bigint];
  export interface OutputObject {
    chainId: bigint;
    protocolFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeDistributedEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [token: string, amount: bigint, recipient: string];
  export interface OutputObject {
    token: string;
    amount: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeTierAddedEvent {
  export type InputTuple = [
    minAmount: BigNumberish,
    maxAmount: BigNumberish,
    feeBps: BigNumberish
  ];
  export type OutputTuple = [
    minAmount: bigint,
    maxAmount: bigint,
    feeBps: bigint
  ];
  export interface OutputObject {
    minAmount: bigint;
    maxAmount: bigint;
    feeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryWalletUpdatedEvent {
  export type InputTuple = [oldWallet: AddressLike, newWallet: AddressLike];
  export type OutputTuple = [oldWallet: string, newWallet: string];
  export interface OutputObject {
    oldWallet: string;
    newWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TreasuryFeeCollector extends BaseContract {
  connect(runner?: ContractRunner | null): TreasuryFeeCollector;
  waitForDeployment(): Promise<this>;

  interface: TreasuryFeeCollectorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  FEE_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  GOVERNANCE_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  addFeeTier: TypedContractMethod<
    [minAmount: BigNumberish, maxAmount: BigNumberish, feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  chainFeeConfigs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        protocolFeeBps: bigint;
        relayerFeeBps: bigint;
        bridgeFeeBps: bigint;
        treasuryFeeBps: bigint;
        enabled: boolean;
      }
    ],
    "view"
  >;

  collectFee: TypedContractMethod<
    [
      routeId: BytesLike,
      token: AddressLike,
      amount: BigNumberish,
      chainId: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  distributeToTreasury: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeTiers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        minAmount: bigint;
        maxAmount: bigint;
        feeBps: bigint;
      }
    ],
    "view"
  >;

  getFee: TypedContractMethod<[routeId: BytesLike], [bigint], "view">;

  getFeeForAmount: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTokenFees: TypedContractMethod<
    [token: AddressLike],
    [TreasuryFeeCollector.FeeCollectionStructOutput],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  minFeeTier: TypedContractMethod<[], [bigint], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  routeFees: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  setFeeConfig: TypedContractMethod<
    [
      chainId: BigNumberish,
      protocolFeeBps: BigNumberish,
      relayerFeeBps: BigNumberish,
      bridgeFeeBps: BigNumberish,
      treasuryFeeBps: BigNumberish,
      enabled: boolean
    ],
    [void],
    "nonpayable"
  >;

  setTreasuryWallet: TypedContractMethod<
    [_treasuryWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  tokenFees: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint] & {
        token: string;
        totalCollected: bigint;
        distributedToRelayers: bigint;
        distributedToTreasury: bigint;
        lastCollection: bigint;
      }
    ],
    "view"
  >;

  treasuryWallet: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FEE_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GOVERNANCE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addFeeTier"
  ): TypedContractMethod<
    [minAmount: BigNumberish, maxAmount: BigNumberish, feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "chainFeeConfigs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        protocolFeeBps: bigint;
        relayerFeeBps: bigint;
        bridgeFeeBps: bigint;
        treasuryFeeBps: bigint;
        enabled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "collectFee"
  ): TypedContractMethod<
    [
      routeId: BytesLike,
      token: AddressLike,
      amount: BigNumberish,
      chainId: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributeToTreasury"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeTiers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        minAmount: bigint;
        maxAmount: bigint;
        feeBps: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFee"
  ): TypedContractMethod<[routeId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFeeForAmount"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTokenFees"
  ): TypedContractMethod<
    [token: AddressLike],
    [TreasuryFeeCollector.FeeCollectionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "minFeeTier"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "routeFees"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setFeeConfig"
  ): TypedContractMethod<
    [
      chainId: BigNumberish,
      protocolFeeBps: BigNumberish,
      relayerFeeBps: BigNumberish,
      bridgeFeeBps: BigNumberish,
      treasuryFeeBps: BigNumberish,
      enabled: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasuryWallet"
  ): TypedContractMethod<[_treasuryWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tokenFees"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint] & {
        token: string;
        totalCollected: bigint;
        distributedToRelayers: bigint;
        distributedToTreasury: bigint;
        lastCollection: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "treasuryWallet"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FeeCollected"
  ): TypedContractEvent<
    FeeCollectedEvent.InputTuple,
    FeeCollectedEvent.OutputTuple,
    FeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "FeeConfigUpdated"
  ): TypedContractEvent<
    FeeConfigUpdatedEvent.InputTuple,
    FeeConfigUpdatedEvent.OutputTuple,
    FeeConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeDistributed"
  ): TypedContractEvent<
    FeeDistributedEvent.InputTuple,
    FeeDistributedEvent.OutputTuple,
    FeeDistributedEvent.OutputObject
  >;
  getEvent(
    key: "FeeTierAdded"
  ): TypedContractEvent<
    FeeTierAddedEvent.InputTuple,
    FeeTierAddedEvent.OutputTuple,
    FeeTierAddedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryWalletUpdated"
  ): TypedContractEvent<
    TreasuryWalletUpdatedEvent.InputTuple,
    TreasuryWalletUpdatedEvent.OutputTuple,
    TreasuryWalletUpdatedEvent.OutputObject
  >;

  filters: {
    "FeeCollected(bytes32,address,uint256,uint256)": TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;
    FeeCollected: TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;

    "FeeConfigUpdated(uint256,uint256)": TypedContractEvent<
      FeeConfigUpdatedEvent.InputTuple,
      FeeConfigUpdatedEvent.OutputTuple,
      FeeConfigUpdatedEvent.OutputObject
    >;
    FeeConfigUpdated: TypedContractEvent<
      FeeConfigUpdatedEvent.InputTuple,
      FeeConfigUpdatedEvent.OutputTuple,
      FeeConfigUpdatedEvent.OutputObject
    >;

    "FeeDistributed(address,uint256,address)": TypedContractEvent<
      FeeDistributedEvent.InputTuple,
      FeeDistributedEvent.OutputTuple,
      FeeDistributedEvent.OutputObject
    >;
    FeeDistributed: TypedContractEvent<
      FeeDistributedEvent.InputTuple,
      FeeDistributedEvent.OutputTuple,
      FeeDistributedEvent.OutputObject
    >;

    "FeeTierAdded(uint256,uint256,uint256)": TypedContractEvent<
      FeeTierAddedEvent.InputTuple,
      FeeTierAddedEvent.OutputTuple,
      FeeTierAddedEvent.OutputObject
    >;
    FeeTierAdded: TypedContractEvent<
      FeeTierAddedEvent.InputTuple,
      FeeTierAddedEvent.OutputTuple,
      FeeTierAddedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TreasuryWalletUpdated(address,address)": TypedContractEvent<
      TreasuryWalletUpdatedEvent.InputTuple,
      TreasuryWalletUpdatedEvent.OutputTuple,
      TreasuryWalletUpdatedEvent.OutputObject
    >;
    TreasuryWalletUpdated: TypedContractEvent<
      TreasuryWalletUpdatedEvent.InputTuple,
      TreasuryWalletUpdatedEvent.OutputTuple,
      TreasuryWalletUpdatedEvent.OutputObject
    >;
  };
}
